name: candlesticks
description: A high-performance full featured candlesticks chart for all platforms.
version: 1.0.2
homepage: https://github.com/Ahmed-Habeeb/candels

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: